### ISSUE TITLE
release？

### ISSUE THREAD

**Issue by winxpqq955** [NoobPvPerL/NoobClicker#2]
醉了，挂狗不会编译，能不能快点发release啊

**Comment by NoobPvPerL** [comment]
Noobclicker因为打包了Qt所需的dll因此内存为63mb github没梯子发确实比较烦人 btw我电脑可能周末能碰我干脆发b站吧

**Comment by NoobPvPerL** [comment]
而且你妈能不能star一下

**Comment by winxpqq955** [comment]
> 而且你妈能不能star一下

star了别人看到会觉得我品味差
