### ISSUE TITLE
How can i run this clicker?

### ISSUE THREAD

**Issue by wephtz** [NoobPvPerL/NoobClicker#6]
I put it in Visual Studio Code and there's many things the same as on the website like:png files, readme, noobclicker.pro etc.. so how can i run this clicker to make it work in minecraft
sorry for the stupid question

**Comment by NoobPvPerL** [comment]
Hello.This program was coded on Qt,Visual Studio doesn't support Qt programs.Therefore,you may have to visit qt.io and then download the Qt,and open noobclicker.pro when Qt has successfully installed on your PC.

P.S.
If you just wanna run NoobClicker on your PC,you only need to download the release:https://github.com/NoobPvPerL/NoobClicker/releases/download/v2.0/NoobClicker.v2.0.32bits.exe

**Comment by wephtz** [comment]
> Hello.This program was coded on Qt,Visual Studio doesn't support Qt programs.Therefore,you may have to visit qt.io and then download the Qt,and open noobclicker.pro when Qt has successfully installed on your PC.
> 
> P.S.
> If you just wanna run NoobClicker on your PC,you only need to download the release:https://github.com/NoobPvPerL/NoobClicker/releases/download/v2.0/NoobClicker.v2.0.32bits.exe

thanks a lot to you <3

**Comment by wephtz** [comment]
hey can i somehow fix that its clicking with some cooldown, if u not aiming to player?

**Comment by NoobPvPerL** [comment]
What Minecraft version do you use

**Comment by wephtz** [comment]
> What Minecraft version do you use
1.8.9

**Comment by NoobPvPerL** [comment]
Minecraft 1.8.9 has changed the method of clicking, so this clicker only work on 1.7 and below
